---
- name: "Adding the user {{ jenkins_config_owner  }}"
  user:
    name: "{{ jenkins_config_owner }}"
    shell: /bin/bash
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: "creating jenkings working directory {{ jenkins_home }}"
  file:
    path: "{{ jenkins_home }}"
    state: directory
    mode: 0755
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
