
- name: "creating jenkings tmp directory"
  file:
    path: /var/lib/docker/tmp/
    state: directory
    mode: 0755
    owner: "{{ uid }}"
    group: "{{ gid }}"

- name: "creating jenkings working directory {{ jenkins_home }}"
  file:
    path: "{{ jenkins_home }}"
    state: directory
    mode: 0755
    owner: "{{ uid }}"
    group: "{{ gid }}"

- name: "creating jenkings working directory {{ jenkins_logs }}"
  file:
    path: "{{ jenkins_logs }}"
    state: directory
    mode: 0755
    owner: "{{ uid }}"
    group: "{{ gid }}"

- name: "creating apache tls directory {{ nginx_tls }}"
  file:
    path: "{{ nginx_tls }}"
    state: directory
    mode: 0755
    owner: "{{ uid }}"
    group: "{{ gid }}"

- name: copy down server_key to /app dir
  copy:
    content: "{{ server_key.value }}"
    dest: "{{ nginx_tls }}/server.key"

- name: copy down server_cert to /app dir
  copy:
    content: "{{ server_cert.value }}"
    dest: "{{ nginx_tls }}/server.ctr"

- name: Copy the docker compose configuration file for docker.
  template:
    src: docker-compose.yaml.j2
    dest: /app/docker-compose.yaml

- name: Copy the logging configuration file for jenkins.
  template:
    src: logging.properties.j2
    dest: /app/logging.properties

- name: Copy the logging configuration file for apache.
  template:
    src: default.conf.j2
    dest: /app/default.conf
