---
# If precommit is not installed
# Please run "brew install pre-commit"
- repo: local
  hooks:
  -   id: ansible-lint
      name: Ansible-lint
      description: This hook runs ansible-lint.
      entry: ansible-lint
      language: python
      files: \.(yaml|yml)$
