- name: Create a user jenkins and 2048-bit SSH key in ~/.ssh/id_rsa
  user:
    name: jenkins
    state: present
  notify:
    - creating jenkings authorized_keys file

- name: "creating jenkings authorized_keys file"
  copy:
    content: "{{ jenkins_authorized_key.public_key }}"
    dest: "{{ jenkins_authorized_key_path }}"
    mode: 0600
    owner: "jenkins"

- name: copy down docker_hub creds
  copy:
    content: "{{ dockercfg.docker_hub }}"
    dest: "{{ dockercfg_path }}"
