- name: Create a user jenkins and 2048-bit SSH key in ~/.ssh/id_rsa
  user:
    name: jenkins
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    groups: docker,root
    append: yes

- name: "creating jenkings authorized_keys file"
  copy:
    content: "{{ jenkins_authorized_key.public_key }}"
    dest: "{{ jenkins_authorized_key_path }}"
    mode: 0600
    owner: "jenkins"

- name: copy down docker_hub creds
  copy:
    content: "{{ dockercfg.docker_hub }}"
    dest: "{{ dockercfg_path }}"
