FROM jenkins:{{ jenkins_version }}

COPY plugins.txt /usr/share/jenkins/plugins.txt
COPY install_jenkins_plugin.sh /usr/local/bin/install_jenkins_plugin.sh
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/install_jenkins_plugin.sh
